
package interfaces;

import modelos.Usuario;
import sql.ExportarExcel;
import sql.RegistroDAO;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mayck
 */
public class RegistroDigital extends javax.swing.JDialog {

    /**
     * Creates new form Relatorios
     */
    RegistroDAO projeto = new RegistroDAO();
    static int linha_selecionada = 0;
    static String linhaRegistro = "0";
    
    public RegistroDigital(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();        
        projeto.getRegistro("");
        inicializar();
    }
    
    public void inicializar()
    {
        desabilitaTudo();
        labelMensagem.setVisible(false);  
    }
    
    public void habilitaTudo()
    {
        btnEditar.setEnabled(true);
        btnRemover.setEnabled(true);
        btnAbrirImprimir.setEnabled(true);
        btnEnviar.setEnabled(true);
    }
    public void desabilitaTudo()
    {
        btnEditar.setEnabled(false);
        btnRemover.setEnabled(false);
        btnAbrirImprimir.setEnabled(false);
        btnEnviar.setEnabled(false);
    }
    public void removerRegistro()
    {
       int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover esse registro?", "Remover registro", JOptionPane.YES_NO_OPTION);

        switch (resposta) 
        {
            case 0:
                RegistroDAO registro = new RegistroDAO();
                registro.deletarRegistro(linhaRegistro);
                linhaRegistro = "0";
                registro.getRegistro("");
                break;
            case 1:
                break;
            default:
                break;
        }
      }
    
    
        
    public void exportar()
    {
        if(RegistroDigital.jTableRegistroDigital.getRowCount() == 0)
        {
            JOptionPane.showMessageDialog(null, "Não há dados na tabela para exportar.","Mayck Lima",JOptionPane.INFORMATION_MESSAGE);
        }else{
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos de excel","xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar arquivo");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        
        if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION)
        {
            List<JTable> tb = new ArrayList<>();
            List<String> nome = new ArrayList<>();
            tb.add(jTableRegistroDigital);
            nome.add("Registro Digital");
            String file = chooser.getSelectedFile().toString().concat(".xls");
            
            try {
                ExportarExcel e = new ExportarExcel(new File(file),tb,nome);
                if(e.exportar()){
                    JOptionPane.showMessageDialog(null, "Os dados foram exportados");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
            
    }
    public void editar()
    {        
        desabilitaTudo();
        if(linhaRegistro.equals("0"))
        {
            labelMensagem.setVisible(true);
            labelMensagem.setText("Selecione uma linha");
            labelMensagem.setBackground(new Color(255,102,0));
        }else
        {
            JFrame mainFrame = new JFrame();
            AlterarRegistro alterarRegistro = new AlterarRegistro(mainFrame, true);
            alterarRegistro.setLocationRelativeTo(mainFrame);
            alterarRegistro.setVisible(true);
        }
    }
    public void enviar()
    {
        JFrame mainFrame = new JFrame();
        EnviarEmail enviar = new EnviarEmail(mainFrame, true);
        enviar.setLocationRelativeTo(mainFrame);
        enviar.setVisible(true);
    }
    
     public void abrirGmail()
        {
            JFrame mainFrame = new JFrame();
            Gmail gmail = new Gmail(mainFrame, true);
            gmail.setLocationRelativeTo(mainFrame);
            gmail.setVisible(true);
        }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        menuEnviar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();
        menuRemover = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistroDigital = new javax.swing.JTable();
        txtPesquisarRegistro = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        exportar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        labelMensagem = new javax.swing.JLabel();
        labelRegistro = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnGmail = new javax.swing.JButton();
        btnAbrirImprimir = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        menuEnviar.setText("Enviar por email...");
        menuEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnviarActionPerformed(evt);
            }
        });
        popUp.add(menuEnviar);

        menuEditar.setText("Editar registro");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        popUp.add(menuEditar);

        menuRemover.setText("Remover registro");
        menuRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoverActionPerformed(evt);
            }
        });
        popUp.add(menuRemover);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Protocolo - DPGPI");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(null);

        jTableRegistroDigital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRegistroDigital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRegistroDigitalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableRegistroDigitalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableRegistroDigitalMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRegistroDigital);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 1230, 480);

        txtPesquisarRegistro.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisarRegistro.setText("Pesquisar...");
        txtPesquisarRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisarRegistroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisarRegistroFocusLost(evt);
            }
        });
        txtPesquisarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarRegistroActionPerformed(evt);
            }
        });
        txtPesquisarRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarRegistroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarRegistroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisarRegistroKeyTyped(evt);
            }
        });
        getContentPane().add(txtPesquisarRegistro);
        txtPesquisarRegistro.setBounds(830, 40, 350, 30);

        btnPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisa.png"))); // NOI18N
        btnPesquisar.setToolTipText("Clique para pesquisar por um registro");
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(1180, 40, 60, 30);

        exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excel.png"))); // NOI18N
        exportar.setText("Exportar");
        exportar.setToolTipText("Clique para exportar a tabela de registros");
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });
        getContentPane().add(exportar);
        exportar.setBounds(1140, 80, 100, 30);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        btnAdicionar.setText("Adicionar registro");
        btnAdicionar.setToolTipText("Clique para adicionar um registro");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(340, 600, 160, 32);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        btnEditar.setText("Editar registro");
        btnEditar.setToolTipText("Clique para editar um registro");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(510, 600, 160, 32);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_projeto.png"))); // NOI18N
        btnRemover.setText("Remover registro");
        btnRemover.setToolTipText("Clique para remover um registro");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(680, 600, 160, 32);

        labelMensagem.setBackground(new java.awt.Color(0, 204, 51));
        labelMensagem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMensagem.setForeground(new java.awt.Color(255, 255, 255));
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem.setFocusable(false);
        labelMensagem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelMensagem.setOpaque(true);
        getContentPane().add(labelMensagem);
        labelMensagem.setBounds(0, 0, 1270, 30);

        labelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        labelRegistro.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        labelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistro.setText("Protocolo - DPGPI");
        labelRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelRegistro.setOpaque(true);
        getContentPane().add(labelRegistro);
        labelRegistro.setBounds(-10, -10, 1280, 90);

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sendemail.png"))); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(1080, 600, 160, 32);

        btnGmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gmail.png"))); // NOI18N
        btnGmail.setText("Configurar Gmail");
        btnGmail.setToolTipText("Clique para adicionar um registro");
        btnGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGmailActionPerformed(evt);
            }
        });
        getContentPane().add(btnGmail);
        btnGmail.setBounds(20, 600, 160, 32);

        btnAbrirImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print.png"))); // NOI18N
        btnAbrirImprimir.setText("Abrir/Imprimir");
        btnAbrirImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrirImprimir);
        btnAbrirImprimir.setBounds(950, 600, 130, 32);

        bg.setBackground(new java.awt.Color(236, 236, 236));
        bg.setOpaque(true);
        getContentPane().add(bg);
        bg.setBounds(0, -6, 1270, 660);

        setBounds(0, 0, 1268, 685);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroActionPerformed

    }//GEN-LAST:event_txtPesquisarRegistroActionPerformed

    private void txtPesquisarRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroKeyPressed
       // projeto.getRegistro(txtPesquisarRegistro.getText());
       // linhaRegistro = "0";
    }//GEN-LAST:event_txtPesquisarRegistroKeyPressed

    private void txtPesquisarRegistroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroKeyReleased
       // projeto.getRegistro(txtPesquisarRegistro.getText());
        // linhaRegistro = "0";
    }//GEN-LAST:event_txtPesquisarRegistroKeyReleased

    private void txtPesquisarRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroKeyTyped
        projeto.getRegistro(txtPesquisarRegistro.getText());
         linhaRegistro = "0";
    }//GEN-LAST:event_txtPesquisarRegistroKeyTyped

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        projeto.getRegistro(txtPesquisarRegistro.getText());
        linhaRegistro = "0";
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
      exportar();
    }//GEN-LAST:event_exportarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        JFrame mainFrame = new JFrame();
        CadastrarRegistro ad = new CadastrarRegistro(mainFrame, true);
        ad.setLocationRelativeTo(mainFrame);
        ad.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
      if(linhaRegistro.equals("0"))
      {
          labelMensagem.setVisible(true);
          labelMensagem.setText("Selecione uma linha");
          labelMensagem.setBackground(new Color(255,102,0));
      }else{
           desabilitaTudo();
        removerRegistro();
      }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void jTableRegistroDigitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegistroDigitalMouseClicked
           if(jTableRegistroDigital.getSelectedRow() >= 0)
            {
                linha_selecionada = jTableRegistroDigital.getSelectedRow();
                linhaRegistro = (String.valueOf(jTableRegistroDigital.getValueAt(linha_selecionada, 0)));
                labelMensagem.setVisible(false);
                habilitaTudo();
            }else
            {
            }  
    }//GEN-LAST:event_jTableRegistroDigitalMouseClicked

    private void jTableRegistroDigitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegistroDigitalMousePressed
            if(jTableRegistroDigital.getSelectedRow() >= 0)
            {
                linha_selecionada = jTableRegistroDigital.getSelectedRow();
                linhaRegistro = (String.valueOf(jTableRegistroDigital.getValueAt(linha_selecionada, 0)));
                labelMensagem.setVisible(false);
                habilitaTudo();
            }else
            {
            }  
    }//GEN-LAST:event_jTableRegistroDigitalMousePressed

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        editar();
    }//GEN-LAST:event_menuEditarActionPerformed

    private void menuRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoverActionPerformed
        removerRegistro();
    }//GEN-LAST:event_menuRemoverActionPerformed

    private void jTableRegistroDigitalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegistroDigitalMouseReleased
    if(jTableRegistroDigital.getSelectedRow() >= 0)
    {  
        if(evt.isPopupTrigger())
        {
            popUp.show(jTableRegistroDigital, evt.getX(), evt.getY()); 
            labelMensagem.setVisible(false);
        }
    }else
    {
    }
    }//GEN-LAST:event_jTableRegistroDigitalMouseReleased

    private void menuEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnviarActionPerformed
    enviar();
        
    }//GEN-LAST:event_menuEnviarActionPerformed

    private void txtPesquisarRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroFocusGained
        txtPesquisarRegistro.setText("");
        txtPesquisarRegistro.setForeground(Color.black);
        labelMensagem.setVisible(false);
    }//GEN-LAST:event_txtPesquisarRegistroFocusGained

    private void txtPesquisarRegistroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroFocusLost
        txtPesquisarRegistro.setText("Pesquisar...");
        txtPesquisarRegistro.setForeground(Color.GRAY);
    }//GEN-LAST:event_txtPesquisarRegistroFocusLost

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        desabilitaTudo();
        enviar();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnAbrirImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirImprimirActionPerformed
        desabilitaTudo();        
        if(linhaRegistro.equals("0"))
        {
            labelMensagem.setVisible(true);
            labelMensagem.setText("Selecione uma linha");
            labelMensagem.setBackground(new Color(255,102,0));
        }else{
            try
            {
            String pasta = String.valueOf(jTableRegistroDigital.getValueAt(linha_selecionada, 7));
            String nome = String.valueOf(jTableRegistroDigital.getValueAt(linha_selecionada, 1));
            int registro = Integer.parseInt(String.valueOf(jTableRegistroDigital.getValueAt(linha_selecionada, 0)));
            String arq = Usuario.getSalvar_em() + "\\" + pasta + "\\" + registro + "-"+ nome +".pdf";
            System.out.println(arq);  
                if(new File(arq).exists())
                {
                    File diretorio = new File(arq);
                    Desktop.getDesktop().open(new File(diretorio + ""));
                }else
                {
                    JOptionPane.showMessageDialog(null, "Não foi possível encontrar o certificado do participante " + nome);
                }

            } catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, "Arquivo não encontrado" + ex);
            }
        }

    }//GEN-LAST:event_btnAbrirImprimirActionPerformed

    private void btnGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGmailActionPerformed
        abrirGmail();
    }//GEN-LAST:event_btnGmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroDigital dialog = new RegistroDigital(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAbrirImprimir;
    public static javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEnviar;
    public static javax.swing.JButton btnGmail;
    private static javax.swing.JButton btnPesquisar;
    public javax.swing.JButton btnRemover;
    private javax.swing.JButton exportar;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableRegistroDigital;
    public static javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelRegistro;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuEnviar;
    private javax.swing.JMenuItem menuRemover;
    private javax.swing.JPopupMenu popUp;
    private javax.swing.JTextField txtPesquisarRegistro;
    // End of variables declaration//GEN-END:variables
}
